# Generated by Django 4.1.3 on 2022-11-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosutumUser',
            fields=[
                ('CosutumUserId', models.BigAutoField(primary_key=True, serialize=False)),
                ('Prenom', models.CharField(max_length=45)),
                ('Nom', models.CharField(max_length=45)),
                ('Type', models.CharField(max_length=10)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numéro_employé', models.CharField(max_length=45)),
                ('jours_travaillés', models.IntegerField(default=None)),
                ('date_embauche', models.DateField()),
                ('date_demission', models.DateField()),
                ('CosutumUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cosutumuser')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_csv', models.FileField(upload_to='')),
                ('traité', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('uploadé_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.employee')),
            ],
        ),
    ]
