# Generated by Django 4.1.3 on 2022-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='jours_travaillés',
            new_name='jours_travailles',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='numéro_employé',
            new_name='numéro_employe',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_csv',
            field=models.FileField(upload_to='App'),
        ),
    ]
