# Generated by Django 4.1.3 on 2022-11-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_jours_travaillés_employee_jours_travailles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='numéro_employe',
            new_name='numero_employe',
        ),
    ]
