# Generated by Django 4.1.3 on 2022-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_numéro_employe_employee_numero_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Cin',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
